[package]
name = "eval"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
colored = "2.0.4"
lexer = { path = "../lexer" }
once_cell = "1.18.0"
parser = { path = "../parser" }
